### ISSUE TITLE
Broken polish translations! Please rollback!

### ISSUE THREAD

**Issue by drakulis** [openatv/enigma2-po#176]
Hi, 

Recently some dude ("@wladyslaw.lam") has added massive changes in polish translations! It looks he just used machine translations EVERYWHERE(!) and has overwritten even all texts translated by community.

Could you please rollback changes in polish translations from following commit and update Weblate accordingly 
[9affe99bf2c248aacb85fea4091cbb5a635735bf](https://github.com/openatv/enigma2-po/commit/9affe99bf2c248aacb85fea4091cbb5a635735bf)

Currently polish translations looks to be translated by monkey. They are inaccurate (translated word by word), or even misleading. I have headache when I have to look on the OpenATV UI now. I had to switch to english.

**Comment by jbleyel** [comment]
DONE

**Comment by jbleyel** [comment]
Please check this -> https://github.com/openatv/enigma2-po/pull/178/files

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/77dbc6fa1bfbc6691e20dbbd495b50649dcb4356#diff-9161a6222bcc9c0d0ecd9e96cfe790439400b21f02695c8ba265267d89d6ab91

**Comment by jbleyel** [comment]
Is it correct now?
Please check and give us a short notice.
Please also contact the other translator and discuss the problems.

**Comment by drakulis** [comment]
Hi, sorry for late response. Yes it looks good. I mean this commit: https://github.com/openatv/enigma2/commit/77dbc6fa1bfbc6691e20dbbd495b50649dcb4356#diff-9161a6222bcc9c0d0ecd9e96cfe790439400b21f02695c8ba265267d89d6ab91

But I didn't get updated translations on my STB yet. Waiting for new release.

I have already wrote an email to @wladyslaw.lam but he did not respond.
