### ISSUE TITLE
correction of translation ru.po

### ISSUE THREAD

**Issue by Marchella1983** [openatv/enigma2-po#207]
please correct these lines
`
msgid "Show 2160p 24fps as"
msgstr "Показать 720p 24fps как"

msgid "Show 2160p 25fps as"
msgstr "Показать 1080p 25fps как"

msgid "Show 2160p 30fps as"
msgstr "Показать 1080p 30fps как"
`

to
`
msgid "Show 2160p 24fps as"
msgstr "Показать 2160p 24fps как"

msgid "Show 2160p 25fps as"
msgstr "Показать 2160p 25fps как"

msgid "Show 2160p 30fps as"
msgstr "Показать 2160p 30fps как"
`

**Comment by jbleyel** [comment]
You can do this here -> https://hosted.weblate.org/projects/openatv/enigma2-7-0-po/ru/

**Comment by jbleyel** [comment]
You can also search :

https://hosted.weblate.org/translate/openatv/enigma2-7-0-po/ru/?q=Show+2160p&sort_by=-priority%2Cposition&checksum=

**Comment by Marchella1983** [comment]
**@jbleyel** 
Do you believe that?

it's the same as the line
`Show 2160p 24fps as`

would be like. 
`Show 720p 24fps as`

**Comment by jbleyel** [comment]
You misunderstood.
You can change the text by your own on weblate.
