### ISSUE TITLE
Wrong source format in translation enigma.po and missing translation 

### ISSUE THREAD

**Issue by tomzza** [openatv/enigma2-po#218]
8997 msgid "History Zap" correct --> msgid "History Zap..."       Channel zap history page
![History Zap](https://github.com/openatv/enigma2-po/assets/79702804/6c97387f-77c7-4fdc-982e-82fbe3e90235)

And this When you open recordings menu top left corner
msgid "Movie Center"

![movie center](https://github.com/openatv/enigma2-po/assets/79702804/7fecc43d-64c0-4ed9-924a-fe6dcf0e3122)

A few times I manually added Finnish translation, but they disappear every time weblate update source file. 
Is this Correct place report missing translations in source file?

**Comment by jbleyel** [comment]
msgid "History Zap"

msgid "Movie selection"

**Comment by jbleyel** [comment]
msgid "History Zap..." and msgid "Movie Center" is wrong

The msgid entries are automatically generated from the pot file and this will be automatically generated from the source.

**Comment by tomzza** [comment]
Hello, i try again :) automatically generated source is wrong, I also tested the German language there were also missing too translation. I download manually last finnish.po github which was updated there an hour ago, i put it on gigablue 4k quad. Line 9175 wrong letter size: msgid "History zap..." i changed msgid "History Zap..."
![History Zap](https://github.com/openatv/enigma2-po/assets/79702804/f2e18e57-198b-4674-8a32-b4cada1d599e)

Then i added two line finnish.po: 
msgid "Movie Center" 
msgstr "Tallennukset"
Put back gigablue restart and now they converted to Finnish.
Now they both work. Automatically generated from the pot file is wrong need to fix there.
![fixed](https://github.com/openatv/enigma2-po/assets/79702804/9c2b0c79-9438-4409-b428-5c785eace297)

**Comment by jbleyel** [comment]
There is no "Movie Center" in the source. What Image version do you use?

**Comment by jbleyel** [comment]
But I think I have the problem.
There is "Movie Center" in Metrix Skin.

**Comment by jbleyel** [comment]
fixed

https://github.com/openatv/MetrixHD/commit/a55a540a190a750d8d5b3f8dee4a659204b9e6c0

**Comment by tomzza** [comment]
latest 7.3 openATV
