### ISSUE TITLE
[question] Where are OpenATV v7.4 transalations sources located?

### ISSUE THREAD

**Issue by drakulis** [openatv/enigma2-po#327]
Sorry for communication via Github Issues but I do not know how to contact you other way.

More than month ago I have switched my STB to OpenATV 7.4 .I've noticed several issues in Polish translations. I have correct them via Weblate. I've noticed that translations have been already updated in Github repo (this one). I've updated my STB several times since then and I saw that language packages also were also updated (several times) but Polish translations are still outdated.

So, my question is: are OpenATV 7.4 translations stored in different place?

**Comment by jbleyel** [comment]
The translation will be updated in the development version first. The update of the release version will done later.

**Comment by drakulis** [comment]
ok, thx for clarification
